# Generated by Django 5.2.9 on 2025-12-24 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budgets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='取引日')),
                ('description', models.CharField(max_length=255, verbose_name='摘要')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='金額')),
                ('is_living_cost', models.BooleanField(default=False, verbose_name='生活費対象')),
                ('category', models.CharField(blank=True, choices=[('food', '食費'), ('daily', '日用品'), ('utility', '光熱費'), ('rent', '家賃'), ('other', 'その他')], max_length=20, null=True, verbose_name='カテゴリ')),
                ('memo', models.TextField(blank=True, default='', verbose_name='メモ')),
                ('import_hash', models.CharField(max_length=64, unique=True, verbose_name='インポートハッシュ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('monthly_budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='budgets.monthlybudget', verbose_name='対象月')),
                ('payer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_transactions', to=settings.AUTH_USER_MODEL, verbose_name='支払者')),
            ],
            options={
                'verbose_name': '取引明細',
                'verbose_name_plural': '取引明細',
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['monthly_budget'], name='transaction_monthly_aa1df6_idx'), models.Index(fields=['is_living_cost'], name='transaction_is_livi_b67396_idx'), models.Index(fields=['payer'], name='transaction_payer_i_d2dc90_idx'), models.Index(fields=['date'], name='transaction_date_ad8c94_idx')],
            },
        ),
    ]
