# Generated by Django 5.2.9 on 2025-12-24 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.CharField(help_text='YYYY-MM形式', max_length=7, unique=True, verbose_name='対象月')),
                ('income_a', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='ユーザーA月収')),
                ('income_b', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='ユーザーB月収')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_as_a', to=settings.AUTH_USER_MODEL, verbose_name='ユーザーA')),
                ('user_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_as_b', to=settings.AUTH_USER_MODEL, verbose_name='ユーザーB')),
            ],
            options={
                'verbose_name': '月次予算',
                'verbose_name_plural': '月次予算',
                'ordering': ['-year_month'],
            },
        ),
    ]
